--- 
title: "Data Analysis on Income Equality, Financial Indicator and Greenhouse Emission"
author: "Wenbo Zhao, Junfeng Yan, Navjot Singh"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

```{r setup, include=FALSE}
# this prevents package loading message from appearing in the rendered version of your problem set
knitr::opts_chunk$set(warning = FALSE, message = FALSE,
                      echo = TRUE, error = TRUE)
library(tidyverse)
library(patchwork)
```

It has been two years since the outburst of the most devastating pandemic since WWII. According to [WHO dashboard](https://covid19.who.int/), there are more than 250 million cumulative cases and more than 5 millions of cumulative deaths because of Covid-19. Not only is the general public's health severely threatened, but the global economy has heavily suffered as well. The [world bank dataset](https://data.worldbank.org/indicator/NY.GDP.MKTP.KD.ZG) reported a record-breaking economy decrease of -3.405% in 2020, worse than that of 2009 when economy crisis reached it climax. Unfortunately, the gap between rich and poor has grown wider during the pandemic as well. According to a [report](https://www.census.gov/newsroom/press-releases/2021/income-poverty-health-insurance-coverage.html) by United States Census Bureau, the poverty rate in US is 11.4% in 2020, up 1.0 percentage point from 2019. This is the first increase in poverty after five consecutive annual declines. In contrast, [Forbes world's billionairs list](https://www.forbes.com/billionaires/) shows that the number of billionaires on Forbes’ 35th annual list of the world’s wealthiest exploded to an unprecedented 2,755 --- 660 more than a year ago. It has always been said that education can promote equality, therefore we would like to investigate whether the increase of education attainment and better overall economic condition decrease the income inequality.

Another heated topic in recent times has been the Glasgow Climate Change Conference, also known as [COP26](https://unfccc.int/conference/glasgow-climate-change-conference-october-november-2021). Six years after the landmark Paris Climate Agreement, pending items that prevented the full implementation of the accord on carbon markets and transparency, have finally been approved. According to the [consensus](https://unfccc.int/news/cop26-reaches-consensus-on-key-actions-to-address-climate-change), the duty to fulfill the pledge of providing 100 billion dollars annually from developed to developing countries was also reaffirmed. This drives us to concentrate the relationship between the development condition of a country and its climate influences. Specifically, we investigate whether there is a co-relation between CO2 and financial indicators, quality of life, etc. to find out whether developed countries contributes more greenhouse emissions. Also, we investigate whether richer countries use more renewable sources for electricity production and if this actually reduces the emission of harmful gases. This will help us determine whether richer countries have actually reduced emissions for electricity production or not.